# Setup
title:        从容取舍即优雅
tagline:      Elegance is refusal.
baseurl:      "ldh"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       ldh
  url:        http://yourhomepage.com 

# Build settings
markdown: kramdown
# Gems
plugins:
  - jekyll-paginate
 #- jekyll-feed
#Others
