# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Build settings
markdown: kramdown
# Gems
plugins:
  - jekyll-paginate
 #- jekyll-feed
#Others
